# Generated by Django 5.2.5 on 2025-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_category_image_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
